version: "3.9"
services:
  backend:
    build: ./rentMe_backend
    container_name: rentme-backend
    ports:
      - "8080:8080"
    env_file:
      - ./rentMe_backend/.env

  frontend:
    build: ./rentMe_frontend
    container_name: rentme-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

